version: 0.2

env:
  parameter-store:
    ECR_REPOSITORY_NAME: /CodeBuild/my-nextjs-template/dev/ECR_REPOSITORY_NAME
    DOCKER_USER: /CodeBuild/DOCKER_USER
    DOCKER_TOKEN: /CodeBuild/DOCKER_TOKEN
    DATABASE_URL: /my-nextjs-template/dev/DATABASE_URL
    FIREBASE_PRIVATE_KEY: /my-nextjs-template/dev/FIREBASE_PRIVATE_KEY
    FIREBASE_CLIENT_EMAIL: /my-nextjs-template/dev/FIREBASE_CLIENT_EMAIL
    FIREBASE_PROJECT_ID: /my-nextjs-template/dev/FIREBASE_PROJECT_ID
    FIREBASE_API_KEY: /my-nextjs-template/dev/FIREBASE_API_KEY
    FIREBASE_AUTH_DOMAIN: /my-nextjs-template/dev/FIREBASE_AUTH_DOMAIN
    FIREBASE_STORAGE_BUCKET: /my-nextjs-template/dev/FIREBASE_STORAGE_BUCKET
    FIREBASE_MESSAGING_SENDER_ID: /my-nextjs-template/dev/FIREBASE_MESSAGING_SENDER_ID
    FIREBASE_APP_ID: /my-nextjs-template/dev/FIREBASE_APP_ID

phases:
  install:
    commands:
      - aws --version

  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' | sed -e 's@"@@g')
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com
      - echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin

  build:
    commands:
      - docker build \
        --build-arg database_url="${DATABASE_URL}" \
        --build-arg firebase_private_key="${FIREBASE_PRIVATE_KEY}" \
        --build-arg firebase_client_email="${FIREBASE_CLIENT_EMAIL}" \
        --build-arg firebase_project_id="${FIREBASE_PROJECT_ID}" \
        --build-arg firebase_api_key="${FIREBASE_API_KEY}" \
        --build-arg firebase_auth_domain="${FIREBASE_AUTH_DOMAIN}" \
        --build-arg firebase_storage_bucket="${FIREBASE_STORAGE_BUCKET}" \
        --build-arg firebase_messaging_sender_id="${FIREBASE_MESSAGING_SENDER_ID}" \
        --build-arg firebase_app_id="${FIREBASE_APP_ID}" \
        -t ${ECR_REPOSITORY_NAME} .
      - docker tag ${ECR_REPOSITORY_NAME}:latest ${ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/${ECR_REPOSITORY_NAME}:latest

  post_build:
    commands:
      - docker push ${ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/${ECR_REPOSITORY_NAME}:latest